---- [BASIC] 

-- 1. 춘 기술대학교의 학과 이름과 계열을 표시하시오. 
-- 출력 헤더는 '학과 명', '계열'로 표시
SELECT DEPARTMENT_NAME "학과 명", CATEGORY 계열
FROM TB_DEPARTMENT;

-- 2. 학과의 학과 정원을 다음과 같은 형태로 화면에 출력한다.

SELECT DEPARTMENT_NAME , CAPACITY 
FROM TB_DEPARTMENT 
 ;
 
-- 3. '국어국문학과'에 다니는 여학생 중 휴학중인 여학생 찾자
-- 국문학과의 학과코드는 학과 테이블(TB_DEPARTMENT)을 조회

SELECT STUDENT_NAME
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE ABSENCE_YN = 'Y' AND DEPARTMENT_NO = '001' AND SUBSTR(STUDENT_SSN,8,1) = 2 ;


-- 4. 

SELECT STUDENT_NAME 
FROM TB_STUDENT 
WHERE STUDENT_NO IN('A513079','A513090','A513091','A513110','A513119');

-- 5.
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT 
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR 
WHERE DEPARTMENT_NO IS NULL;

--7.
SELECT STUDENT_NAME
FROM TB_STUDENT 
WHERE DEPARTMENT_NO IS NULL;

--8.
SELECT CLASS_NO
FROM TB_CLASS 
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9.
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT 

--10.

SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT  
WHERE ABSENCE_YN != 'Y' AND STUDENT_ADDRESS LIKE '전주%'  
AND STUDENT_NO LIKE 'A2%';

---- [FUNCTION]

--1.  시분초 어떻게 없애나?

SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_DATE(ENTRANCE_DATE,'rrrr-MM-DD')  입학년도
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = '002'
ORDER BY (ENTRANCE_DATE);

--2. 

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR 
WHERE PROFESSOR_NAME != '___';

-- 3.

SELECT PROFESSOR_NAME 교수이름, ((EXTRACT (YEAR FROM SYSDATE)) - (SUBSTR(PROFESSOR_SSN,1,2)+1900)) 나이
FROM TB_PROFESSOR
ORDER BY 나이 ;















